// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jBAPTyFPbSdsEJ2knWQsPC_MoDbUrbw',
    appId: '1:974452187234:web:39c87cb129a8febfe5713b',
    messagingSenderId: '974452187234',
    projectId: 'mymomsapp-59faa',
    authDomain: 'mymomsapp-59faa.firebaseapp.com',
    storageBucket: 'mymomsapp-59faa.firebasestorage.app',
    measurementId: 'G-R9Z0T7ZHDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7faTdfDqMsj_08PU9Bk9VaclA3mRxNYo',
    appId: '1:974452187234:android:99b4f6bd3c750013e5713b',
    messagingSenderId: '974452187234',
    projectId: 'mymomsapp-59faa',
    storageBucket: 'mymomsapp-59faa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAr_BlZaN_RqT0KNSXo1SOL6YDap_XJ4I',
    appId: '1:974452187234:ios:0bba9df74cdc2190e5713b',
    messagingSenderId: '974452187234',
    projectId: 'mymomsapp-59faa',
    storageBucket: 'mymomsapp-59faa.firebasestorage.app',
    iosBundleId: 'com.example.mvpCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAr_BlZaN_RqT0KNSXo1SOL6YDap_XJ4I',
    appId: '1:974452187234:ios:0bba9df74cdc2190e5713b',
    messagingSenderId: '974452187234',
    projectId: 'mymomsapp-59faa',
    storageBucket: 'mymomsapp-59faa.firebasestorage.app',
    iosBundleId: 'com.example.mvpCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_jBAPTyFPbSdsEJ2knWQsPC_MoDbUrbw',
    appId: '1:974452187234:web:98a94c03f6fca378e5713b',
    messagingSenderId: '974452187234',
    projectId: 'mymomsapp-59faa',
    authDomain: 'mymomsapp-59faa.firebaseapp.com',
    storageBucket: 'mymomsapp-59faa.firebasestorage.app',
    measurementId: 'G-EYEE14JG9J',
  );
}
